### ISSUE TITLE
apk has errors when run on arm64

### ISSUE THREAD

**Issue by kvrhdn** [alpine-docker/git#35] opened 2021-10-06 11:36 UTC
Hi,

We noticed `apk add` commands fail with an error when run on arm64.

You can reproduce this locally if you have access to an ARM machine:

```
$ docker run -it --entrypoint=/bin/sh alpine/git
/git # apk --update --no-cache add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/2) Installing readline (8.1.0-r0)
(2/2) Installing bash (5.1.4-r0)
Executing bash-5.1.4-r0.post-install
Executing busybox-1.33.1-r3.trigger
1 error; 27 MiB in 34 packages
/git # echo $?
1
```

Our workaround is to run `apk fix` before any other apk command, this seems to repair `busybox` and `ca-certificates`:

```
$ docker run -it --entrypoint=/bin/sh alpine/git
/git # apk fix
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/1) Reinstalling ca-certificates (20191127-r5)
Executing busybox-1.33.1-r3.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 25 MiB in 32 packages
/git # apk --update --no-cache add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/2) Installing readline (8.1.0-r0)
(2/2) Installing bash (5.1.4-r0)
Executing bash-5.1.4-r0.post-install
Executing busybox-1.33.1-r3.trigger
OK: 27 MiB in 34 packages
```

Our builds use `alpine/git:latest` and they started failing from Oct 4, 2021, 13:15 UTC. This seems related to the latest merged PR #34.

**Comment by ozbillwang** [comment] 2021-10-06 22:20
if can prove, we can add `apx fix` in Dockerfile

**Comment by ozbillwang** [comment] 2021-10-06 22:40
let me think about if I can add test cases in multi arch via Travis CI. 

https://docs.travis-ci.com/user/multi-cpu-architectures/

**Comment by barthy1** [comment] 2021-10-07 06:43
I can see the same behaviour for `linux/s390x`

```
docker run -it --entrypoint=/bin/sh alpine/git
/git # uname -a
Linux 014cd4d0f800 5.3.7-200.fc30.s390x #1 SMP Fri Oct 18 19:49:30 UTC 2019 s390x Linux
/git # apk --update --no-cache add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/s390x/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/s390x/APKINDEX.tar.gz
(1/2) Installing readline (8.1.0-r0)
(2/2) Installing bash (5.1.4-r0)
Executing bash-5.1.4-r0.post-install
Executing busybox-1.33.1-r3.trigger
2 errors; 28 MiB in 34 packages
```

The problem exists for latest, v2.32.0, and 1.0.31 and doesn't exist for v2.30.2 and 1.0.30

**Comment by ozbillwang** [comment] 2021-10-10 02:10
Finally I saw this issue by my way (with Travis CI multi-arch build support)

![image](https://user-images.githubusercontent.com/8954908/136678732-0d16052f-792e-41c9-af0a-026d294e0727.png)

https://app.travis-ci.com/github/ozbillwang/multi-arch-docker-image-test-case/builds/239494444

**Comment by ozbillwang** [comment] 2021-10-10 04:24
I run the tests. 

when built from my laptop, and push to hub.docker.com, it is fine, what ever I added `apk fix` in `Dockerfile` or not.

But if I built from Travis CI, it always failed to `apk add bash` now.

**Comment by kvrhdn** [comment] 2021-10-12 17:26
Running `apk fix` before any other `apk` commands is fine for us :+1:

**Comment by kvrhdn** [comment] 2022-01-24 12:29
Hi, this issue is showing up again unfortunately. Running `apk fix` in the latest images fails now as well.

Logs from `latest` and `v2.32.0` (the logs are identical):
```
$ docker run -it --entrypoint=/bin/sh alpine/git:v2.32.0
/git # apk fix
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/1) [APK unavailable, skipped] Reinstalling ca-certificates (20191127-r5)
1 error; 25 MiB in 32 packages
```

`v2.30.2` still works without `apk fix`:
```
$ docker run -it --entrypoint=/bin/sh alpine/git:v2.30.2
/git # apk --update --no-cache add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/2) Installing readline (8.1.0-r0)
(2/2) Installing bash (5.1.4-r0)
Executing bash-5.1.4-r0.post-install
Executing busybox-1.33.1-r3.trigger
OK: 27 MiB in 34 packages
```

I'm still running this from an ARM64 system (Apple M1)
```
$ docker run -it --entrypoint=/bin/sh alpine/git:v2.32.0
/git # uname -a
Linux 3dacf3f32152 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 Linux
```

For now, we will try to pin the image we use to `v2.30.2`.

**Comment by ozbillwang** [comment] 2022-01-25 02:16
Thanks for the information and detail. 

There must be some reasons, but not sure anyone know the root cause.

**Comment by ozbillwang** [comment] 2022-08-23 05:31
@kvrhdn 

Do we still have this issue with latest tag [v2.36.2](https://hub.docker.com/layers/git/alpine/git/v2.36.2/images/sha256-77afd5a9d4e2d92c3a82d8313c2f4cf0f043b2b436aa32458d44860e52fd1a24?context=repo) ?

**Comment by ozbillwang** [comment] 2022-09-28 12:29
no reply, close it first

**Closed by ozbillwang** 2022-09-28 12:29 UTC
